baseURL = 'https://b1n-isme.github.io/'
languageCode = 'en-us'
title = 'Linh Nguyen-Truc'
theme = 'barks'

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 2
    [[menu.main]]
        name = "Background"
        url = "/cv/"
        weight = 3
    [[menu.main]]
        name = "Skills"
        url = "/skills/"
        weight = 4

[params]
    author = "Linh Nguyen-Truc"
    description = "AI Engineer Intern at TMA Solutions | Computer Science Student at Vietnamese-German University | Passionate about Computer Vision, NLP, and Machine Learning"
    mainSections = ["projects"]
    
    [params.colors]
        link_color = "#10b981"
    
    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:10421088@student.vgu.edu.vn"
            weight = 1
        [params.social.github]
            name = "GitHub"
            class = "fab fa-github"
            url = "https://github.com/B1n-isme"
            weight = 2
        [params.social.linkedin]
            name = "LinkedIn"
            class = "fab fa-linkedin"
            url = "https://linkedin.com/in/linh-nguyen-truc-166a66186"
            weight = 3
        [params.social.phone]
            name = "Phone"
            class = "fas fa-phone"
            url = "tel:+84867102612"
            weight = 4
